Hw 45 spring boot shopping cart model
GoldHolub/book-store-app pull request #10
Opened 2024-01-20 01:38 UTC by GoldHolub

Added ShoppingCart model to book-store-app

2024-01-20 13:21 UTC, okuzan requested changes

2024-01-20 13:21 UTC, okuzan commented on src/main/java/com/example/demo/service/impl/ShoppingCartServiceImpl.java
> +                        + user.getId()));
extract repeated logic to private utility methods

2024-01-20 13:21 UTC, okuzan commented on src/main/resources/db/changelog/changes/07-create-ShoppingCart-and-CartItem-tables.yaml
> +                nullable: false
make sure to leave exactly one empty line at the EOF

2024-01-20 13:21 UTC, okuzan commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/07-create-ShoppingCart-and-CartItem-tables.yaml
same

2024-01-20 16:52 UTC, sokimaaa commented on src/main/java/com/example/demo/controller/ShoppingCardController.java
> +                                           @RequestBody CartItemUpdateDataRequestDto requestDto) {
Validation here?

2024-01-20 16:54 UTC, sokimaaa commented on src/main/java/com/example/demo/dto/shoppingcard/cartitem/CartItemRequestDto.java
> +@Data
consider using only one approach throughout entire project:
1. creating dto as POJO
2. creating dto as `record`

2024-01-20 16:55 UTC, sokimaaa commented on src/main/java/com/example/demo/model/Book.java
> +    @ManyToMany(fetch = FetchType.EAGER)
use Lazy fetch type for learning purposes

2024-01-21 12:41 UTC, okuzan requested changes

2024-01-21 12:41 UTC, okuzan commented on src/main/java/com/example/demo/service/impl/ShoppingCartServiceImpl.java
> +        }
it's better to throw exception early (invert condition) and unwrap the rest of your code to make it more readable

2024-01-21 12:41 UTC, okuzan commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/07-create-ShoppingCart-and-CartItem-tables.yaml
naming is a bit inconsistent, let's use lowercase with underscore, as in your previous files

2024-01-21 12:41 UTC, okuzan commented on src/main/java/com/example/demo/service/impl/ShoppingCartServiceImpl.java
> +        }
same

2024-01-22 09:57 UTC, merged